[tool.black]
line-length = 119
target-version = ["py310"]

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = false
files = [
    "src",
    "generate.py",
    "rename.py",
    "name2id.py",
    "schedule.py",
    "enclose.py",
    "clean.py",
    "fit.py",
    "transform.py",
]

[tool.coverage.run]
branch = false
source = ["etexood"]

[tool.coverage.report]
exclude_lines = ["pass", "raise NotImplementedError"]

[tool.coverage.html]
directory = ".coverage_html"

[tool.pytest.ini_options]
addopts = "--cov --cov-report html:.coverage_html --cov-report annotate:.coverage_annotate --cov-report term-missing -x"
testpaths = ["src/test"]
