output_dir: experiments/

dataset:
    class: IndNELL9951Trans
    root: ~/ISDEA-main/clone/NBFNet/datasets/
    version: {}

model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32]
    message_func: distmult
    aggregate_func: pna
    short_cut: yes
    layer_norm: yes
    dependent: no

task:
    num_negative: 2
    strict_negative: yes
    adversarial_temperature: 1
    metric: [mr, mrr, hits@1_50, hits@3_50, hits@5_50, hits@10_50, hits@1, hits@3, hits@5, hits@10]


optimizer:
    class: Adam
    lr: 5.0e-3

train:
    gpus: {{ gpus }}
    batch_size: 64
    num_epoch: 50
    log_interval: 100

etexood:
    myid: {{ myid }}
    resume: {{ resume }}
